# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? 14. ??? 14:56:23 2021
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian1qt463\bin\qmake.exe
DEL_FILE          = del
DEL_DIR           = rmdir
MOVE              = move
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtCore" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtCore/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtNetwork" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtNetwork/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtSql" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/QtSql/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/include/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/mkspecs/common/symbian" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/mkspecs/common/symbian/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/osextensions/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/osextensions/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/osextensions/stdapis/stlport" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt463/epoc32/include/stdapis/stlport" -I"C:/Users/user/YandexDisk/td/tdlib/moc" -I"C:/Users/user/YandexDisk/td/tdlib/moc/tmp" -I"C:/Users/user/YandexDisk/td/tdlib" -I"C:/Users/user/YandexDisk/td/tdlib/tmp" -I"C:/Users/user/YandexDisk/td/tdlib/ui" -I"C:/Users/user/YandexDisk/td/tdlib/ui/tmp"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-abld -o "bld.inf" "C:/Users/user/YandexDisk/td/tdlib/tdlib.pro"

bld.inf:
	$(QMAKE)

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp 2> NUL
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

create_temps:
	-@ if NOT EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtCore\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtCore\tmp"
	-@ if NOT EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtNetwork\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtNetwork\tmp"
	-@ if NOT EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtSql\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtSql\tmp"
	-@ if NOT EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\tmp"
	-@ if NOT EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\mkspecs\common\symbian\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\mkspecs\common\symbian\tmp"
	-@ if NOT EXIST "C:\Users\user\YandexDisk\td\tdlib\moc\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\moc\tmp"
	-@ if NOT EXIST "C:\Users\user\YandexDisk\td\tdlib\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\tmp"
	-@ if NOT EXIST "C:\Users\user\YandexDisk\td\tdlib\ui\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\ui\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtCore\tmp" rmdir  /S /Q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtCore\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtNetwork\tmp" rmdir  /S /Q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtNetwork\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtSql\tmp" rmdir  /S /Q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\QtSql\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\tmp" rmdir  /S /Q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\include\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\mkspecs\common\symbian\tmp" rmdir  /S /Q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt463\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\moc\tmp" rmdir  /S /Q  "C:\Users\user\YandexDisk\td\tdlib\moc\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\tmp" rmdir  /S /Q  "C:\Users\user\YandexDisk\td\tdlib\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\ui\tmp" rmdir  /S /Q  "C:\Users\user\YandexDisk\td\tdlib\ui\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps

generated_sources:

all_source_deps: \
	api.h \
	defaults.h \
	TL_serialization_op_codes.h \
	mtproto.h \
	apiquery.h

finalize:

winscw_deployment:

winscw_deployment_clean:

deployment:

deployment_clean:

-include .make.cache

sis:
	$(if $(wildcard tdlib_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(if $(QT_SIS_TARGET),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache)),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_sis:
	createpackage.bat $(QT_SIS_OPTIONS) tdlib_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

tdlib.sis:
	$(MAKE) -s -f $(MAKEFILE) sis

stub_sis:
	$(if $(wildcard tdlib_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_stub_sis,$(if $(QT_SIS_TARGET),$(MAKE) -s -f $(MAKEFILE) ok_stub_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache)),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_stub_sis:
	createpackage.bat -s $(QT_SIS_OPTIONS) tdlib_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

installer_sis: tdlib.sis
	$(if $(wildcard tdlib_installer.pkg),$(MAKE) -s -f $(MAKEFILE) ok_installer_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_installer_sis: 
	createpackage.bat $(QT_SIS_OPTIONS) tdlib_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

fail_sis_nopkg:
	$(error PKG file does not exist, 'sis' and 'installer_sis' target are only supported for executables or projects with DEPLOYMENT statement)

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

store_build:
	@echo # ============================================================================== > .make.cache
	@echo # This file is generated by make and should not be modified by the user >> .make.cache
	@echo #  Name        : .make.cache >> .make.cache
	@echo #  Part of     : tdlib >> .make.cache
	@echo #  Description : This file is used to cache last build target for >> .make.cache
	@echo #                make sis target. >> .make.cache
	@echo #  Version     :  >> .make.cache
	@echo # >> .make.cache
	@echo # ============================================================================== >> .make.cache
	@echo. >> .make.cache
	@echo QT_SIS_TARGET ?= $(QT_SIS_TARGET) >> .make.cache

dodistclean:
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\Makefile" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\Makefile"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\Makefile_0xEae60e83.mk" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\Makefile_0xEae60e83.mk"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\tdlib_0xEae60e83.mmp" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\tdlib_0xEae60e83.mmp"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\.make.cache" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\.make.cache"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\bld.inf" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\bld.inf"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

clean-debug: $(ABLD)
	$(ABLD) reallyclean winscw udeb
	$(ABLD) reallyclean gcce udeb
	$(ABLD) reallyclean armv5 udeb
	$(ABLD) reallyclean armv6 udeb

clean-release: $(ABLD)
	$(ABLD) reallyclean gcce urel
	$(ABLD) reallyclean armv5 urel
	$(ABLD) reallyclean armv6 urel

clean-debug-winscw: $(ABLD)
	$(ABLD) reallyclean winscw udeb
clean-debug-gcce: $(ABLD)
	$(ABLD) reallyclean gcce udeb
clean-debug-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 udeb
clean-debug-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 udeb
clean-release-gcce: $(ABLD)
	$(ABLD) reallyclean gcce urel
clean-release-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 urel
clean-release-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 urel

