#############################################################################
# Makefile for building: tdlib
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 8. ??? 22:43:05 2020
# Project:  tdlib.pro
# Template: lib
# Command: c:\qtsdk\symbian\sdks\symbian1qt473\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf tdlib.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian1qt473\bin\qmake.exe
DEL_FILE          = del 2> NUL
DEL_DIR           = rmdir
MOVE              = move
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtCore" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtCore/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtNetwork" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtNetwork/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtSql" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtSql/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/mkspecs/common/symbian" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/mkspecs/common/symbian/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis/stlport" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis/stlport" -I"C:/Users/user/YandexDisk/td/tdlib/moc" -I"C:/Users/user/YandexDisk/td/tdlib/moc/tmp" -I"C:/Users/user/YandexDisk/td/tdlib" -I"C:/Users/user/YandexDisk/td/tdlib/tmp" -I"C:/Users/user/YandexDisk/td/tdlib/ui" -I"C:/Users/user/YandexDisk/td/tdlib/ui/tmp"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) "C:/Users/user/YandexDisk/td/tdlib/tdlib.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/user/YandexDisk/td/tdlib/tdlib.pro
	$(QMAKE) "C:/Users/user/YandexDisk/td/tdlib/tdlib.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

check: first

sis:

store_build:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

create_temps:
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtNetwork\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtNetwork\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtSql\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtSql\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp"
	-@ if not exist "C:\Users\user\YandexDisk\td\tdlib\moc\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\moc\tmp"
	-@ if not exist "C:\Users\user\YandexDisk\td\tdlib\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\tmp"
	-@ if not exist "C:\Users\user\YandexDisk\td\tdlib\ui\tmp" mkdir "C:\Users\user\YandexDisk\td\tdlib\ui\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtNetwork\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtNetwork\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtSql\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtSql\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\moc\tmp" rmdir /s /q  "C:\Users\user\YandexDisk\td\tdlib\moc\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\tmp" rmdir /s /q  "C:\Users\user\YandexDisk\td\tdlib\tmp"
	-@ if EXIST "C:\Users\user\YandexDisk\td\tdlib\ui\tmp" rmdir /s /q  "C:\Users\user\YandexDisk\td\tdlib\ui\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps

generated_sources:

all_source_deps: \
	api.h

finalize:

winscw_deployment:

winscw_deployment_clean:

deployment:

deployment_clean:

dodistclean:
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\Makefile" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\Makefile"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\Makefile_tdlib_lib.mk" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\Makefile_tdlib_lib.mk"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\tdlib_lib.mmp" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\tdlib_lib.mmp"
	-@ if EXIST "c:\Users\user\YandexDisk\td\tdlib\bld.inf" $(DEL_FILE)  "c:\Users\user\YandexDisk\td\tdlib\bld.inf"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

clean-debug: $(ABLD)
	$(ABLD) reallyclean winscw udeb
	$(ABLD) reallyclean gcce udeb
	$(ABLD) reallyclean armv5 udeb
	$(ABLD) reallyclean armv6 udeb

clean-release: $(ABLD)
	$(ABLD) reallyclean gcce urel
	$(ABLD) reallyclean armv5 urel
	$(ABLD) reallyclean armv6 urel

clean-debug-winscw: $(ABLD)
	$(ABLD) reallyclean winscw udeb
clean-debug-gcce: $(ABLD)
	$(ABLD) reallyclean gcce udeb
clean-debug-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 udeb
clean-debug-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 udeb
clean-release-gcce: $(ABLD)
	$(ABLD) reallyclean gcce urel
clean-release-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 urel
clean-release-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 urel

freeze: $(ABLD)
	$(ABLD) freeze

freeze-debug: freeze

freeze-release: freeze

freeze-debug-winscw: $(ABLD)
	$(ABLD) freeze winscw
freeze-debug-gcce: $(ABLD)
	$(ABLD) freeze gcce
freeze-debug-armv5: $(ABLD)
	$(ABLD) freeze armv5
freeze-debug-armv6: $(ABLD)
	$(ABLD) freeze armv6
freeze-release-gcce: $(ABLD)
	$(ABLD) freeze gcce
freeze-release-armv5: $(ABLD)
	$(ABLD) freeze armv5
freeze-release-armv6: $(ABLD)
	$(ABLD) freeze armv6

